UI/dashboard polish
Kareadita/Kavita pull request #1407
Opened 2022-08-08 01:45 UTC by TheIceCreamTroll

# Changed
- Changed: Save buttons on user and admin dashboards will only activate if a setting is changed, and will deactivate when clicked (addresses [#1395](https://github.com/Kareadita/Kavita/issues/1395)).
- Changed: The save button on the password reset screen will only activate if 'New Password' and 'Confirm Password' match  (addresses [#1395](https://github.com/Kareadita/Kavita/issues/1395)).
- Changed: Centered user roles to `Roles:` in the admin dashboard (addresses [#1395](https://github.com/Kareadita/Kavita/issues/1395)).

2022-08-08 02:16 UTC, majora2007 commented
Please rename your addresses to fixes. This will automatically close the issues when we merge this branch.

2022-08-08 02:17 UTC, majora2007 commented on UI/Web/src/app/admin/manage-email-settings/manage-email-settings.component.ts
> +      this.settingsForm.markAsPristine();
Move this into the resetForm

2022-08-08 15:37 UTC, TheIceCreamTroll commented
> Please rename your addresses to fixes. This will automatically close the issues when we merge this branch.

This PR only fixes the dashboard-related UI issues in [#1395](https://github.com/Kareadita/Kavita/issues/1395). Some of the other issues there are outside the scope of this PR.

2022-08-12 01:17 UTC, majora2007 commented
This is on my to do for tomorrow morning. If you can fix conflict, would appreciate, but I will test regardless.

2022-08-12 03:13 UTC, TheIceCreamTroll commented
Last minute UI change: Made the ordering of common elements in series and entity info consistent. Also renamed "Read Left" to "Time Left" since "Read Left" is kinda unclear. 

Here's the new order:
![SmallUIChange](https://user-images.githubusercontent.com/33820904/184278225-06c5dced-a9e9-4a8b-b347-9e31ca4f2055.png)

2022-08-12 03:19 UTC, TheIceCreamTroll commented
> This is on my to do for tomorrow morning. If you can fix conflict, would appreciate, but I will test regardless.

Rebased & conflicts resolved

2022-08-12 13:29 UTC, majora2007 requested changes
Your merge removed changes from develop, like Change Password flow: 
![image](https://user-images.githubusercontent.com/735851/184362064-74fcea2b-4fa3-4285-9d2e-7389158c5e6f.png)
vs develop:
![image](https://user-images.githubusercontent.com/735851/184362104-afd57a88-71f7-4d5b-bc4d-89dacbc0c57c.png)

Changing Bookmarks directory isn't enabling the Save button on admin dashboard


Please take care of these (reach out to me if you need help) and ping when ready for a re-review (there is one comment).

2022-08-12 13:29 UTC, majora2007 commented on UI/Web/src/app/admin/manage-users/manage-users.component.html
> +                <div id="user-info">
Don't use ids for styling. Make this a class please.

2022-08-12 21:04 UTC, majora2007 commented
Tested and it looks fine.

2022-08-12 21:28 UTC, merged