Parser optimization part1
Kareadita/Kavita pull request #1531
Opened 2022-09-14 22:33 UTC by tjarls

# Changed
- Changed: Optimized some of the parser methods. CleanTitle is up to 10 times faster.
- Changed: Support additional variants for special keywords "One Shot", "Hors-Série" (Closes #1530 )

# Fixed
- Fixed: Special regexps are now word bound which reduces false positives (Fixes #1529 #1104)

2022-09-14 22:57 UTC, tjarls commented on API/Services/Tasks/Scanner/Parser/Parser.cs
> -    private static string RemoveReleaseGroup(string title)
RemoveReleaseGroup has been dropped entirely since RemoveEditionTagHolders already clears those tags.

2022-09-14 23:02 UTC, tjarls commented on API/Services/Tasks/Scanner/Parser/Parser.cs
>      private static string RemoveMangaSpecialTags(string title)
Those are now one-liners. I left them as their own methods just to make the PR easier to read but we could just add their code into CleanTitle instead and avoid the risk of function call overhead albeit the compiler should optimize those away.

2022-09-14 23:03 UTC, tjarls commented on API/Services/Tasks/Scanner/Parser/Parser.cs
> +    // - non greedy matching of a string where parenthesis are balanced
I need to fix that comment. square brackets instead of parentheis

2022-09-14 23:23 UTC, majora2007 requested changes
I need to give this some dedicated testing and exploration, I will look into this after my current branch is done. 

So far, the changes don't look too bad. Please keep in mind if you're moving forward on other Regex that I plan to replace most Regex with source generators in .net 7, which brings even deeper performance improvements.

2022-09-14 23:23 UTC, majora2007 commented on API/Services/Tasks/Scanner/Parser/DefaultParser.cs
> +        bool isSpecial = type == LibraryType.Comic ? Services.Tasks.Scanner.Parser.Parser.IsComicSpecial(fileName) : Services.Tasks.Scanner.Parser.Parser.IsMangaSpecial(fileName);
Please use var

2022-09-14 23:23 UTC, majora2007 commented on API/Services/Tasks/Scanner/Parser/Parser.cs
> +        title = title.Trim(SpacesAndSeparators);
I like this

2022-09-14 23:23 UTC, majora2007 commented on API/Services/Tasks/Scanner/Parser/Parser.cs
> +        return name.Replace("_", " ");
Couldn't we do name?.Replace() to avoid the if statement?

2022-09-15 13:25 UTC, majora2007 commented
Please add unit tests for all the new individual regex cases you've added, to make maintenance easier. For example, balanced paren, if we can have unit tests for that, it will not only help with maintenance, but also understanding of the code.

2022-09-16 11:59 UTC, tjarls commented
> Please also commit up the Benchmark you're using. I'm sure you're using the Benchmark project I already have setup. We can leave them in and build more on top of them.

For my tests I kept a copy of old `Parser.cs` where I renamed the namespace to in order to perform the comparison. Not exactly what we want long term. I'll post it in a separate branch so that you can take a look before I add the commit here.

Ideally, the bench results would be collected as artifacts during builds within the CI/CD and rely on an external tool to do the comparison between versions. I have no idea what framework would be available to do so within github, unfortunately.

2022-09-16 13:03 UTC, majora2007 commented
Before we merge, to avoid conflicts, can you add a case for #1513? The issue is that CleanTitle strips {} out and since we are now using that as a custom tag in Kavita (and the likelihood of finding it from scene releases is low), we shouldn't strip from Series anymore.

We just need to add 
```
[InlineData("Magic Knight Rayearth {Omnibus Edition} v01 (2011) (Digital) (BlurPixel-Empire)", "Magic Knight Rayearth {Omnibus Edition}")]
```
to our Manga and Comic Parser Tests for Series Name.

2022-09-16 17:48 UTC, tjarls commented
I've added the benchmarking for CleanTitle. The data file is on the large side and may be a concern. Please advise if it should be much smaller.

2022-09-17 18:26 UTC, majora2007 commented
@tjarls I'm just waiting for you to reduce the size of the benchmark data to something like 100 lines and then I think we are good to merge.

2022-09-18 14:46 UTC, majora2007 commented
I'm doing the final round of validation on this then we should be able to merge it today.

2022-09-18 18:26 UTC, merged