Updated Dropdown Menu to allow Nested Menus
Kareadita/Kavita pull request #1554
Opened 2022-09-22 05:34 UTC by KorakotSanti

# Added
- Added: Updated dropdown menu to allow nested menus (#1448)

# Changed
- Changed: Action Factory Service no longer handles attaching actions based on role. The Action Factory Service will generate all possible actions and the dropdown's actions will now be render conditionally based on role as required.
- Changed: Removed download action from the Series Detail dropdown menu as it feels redundant to have a download button next to the dropdown menu button.
- Changed: The layout of the dropdown menu, menu is no longer divided by non-admin actions and admin actions. Some actions are now grouped together into a submenu.

2022-09-22 12:02 UTC, majora2007 requested changes
Overall it looks good. Please take care of my comments. 

Please update your changed to Developer and the notes about changes to Developer:. The pr body should be user facing changes as they are essentially changelongs for the users.

Please use closing syntax on the issue linked so it closes when we merge the PR.

2022-09-22 22:14 UTC, majora2007 commented
From testing, please update the arrow icon to <i class="fa-solid fa-chevron-right"></i>

In addition, on the main page, I'm unable to select the submenu due to hover collapsing. This can be fixed a bit by changing:
```(mouseleave)="preventClick($event); submenu.close()"``` -> 
```
(mouseover)="preventClick($event); subMenuHover.open();" (mouseleave)="preventClick($event)", but the actual solution still needs some work as I don't expect to have 2 sub menus open at once. 
```

On chapter entity, Add to reading list should still fall under Add to parent, to keep a consistent flow with the user:
![image](https://user-images.githubusercontent.com/735851/191857943-fc74736f-5750-4e3c-bd4b-009fe4409503.png)

2022-09-22 22:17 UTC, majora2007 commented
I just solved the menu open/close issue:

```
<ng-template #submenuDropdown>
        <div ngbDropdown #subMenuHover="ngbDropdown" placement="right" (mouseover)="preventClick($event); openSubmenu(action.title, subMenuHover)" (mouseleave)="preventClick($event)">
          <button id="actions-{{action.title}}" class="submenu-toggle" ngbDropdownToggle>{{action.title}} <i class="fa-solid fa-play submenu-icon"></i></button>
          <div ngbDropdownMenu attr.aria-labelledby="actions-{{action.title}}">
            <ng-container *ngTemplateOutlet="submenu; context: { list: action.children }"></ng-container>
          </div>
        </div>
        ```

```
submenu: {[key: string]: NgbDropdown} = {};
openSubmenu(actionTitle: string, subMenu: NgbDropdown) {
    // We keep track when we open and when we get a request to open, if we have other keys, we close them and clear their keys
    if (Object.keys(this.submenu).length > 0) {
      const keys = Object.keys(this.submenu).filter(k => k !== actionTitle);
      keys.forEach(key => {
        this.submenu[key].close();
        delete this.submenu[key];
      });
    }
    this.submenu[actionTitle] = subMenu;
    subMenu.open();
  }
  ````

2022-09-23 05:55 UTC, KorakotSanti commented on UI/Web/src/app/_services/action-factory.service.ts
> +    const actions = this.collectionTagActions.map((a) => {
added the helper function that each of the actions getter calls.

2022-09-23 05:55 UTC, KorakotSanti commented on UI/Web/src/app/_services/action-factory.service.ts
> +        requiresAdmin: true,
done

2022-09-23 05:56 UTC, KorakotSanti commented on UI/Web/src/app/cards/card-item/card-actionables/card-actionables.component.html
> +      </ng-container>
done

2022-09-23 05:59 UTC, KorakotSanti commented on UI/Web/src/app/cards/card-item/card-actionables/card-actionables.component.scss
> +    font-weight: 400;
This variables is actually comes from ngbDropdown, it was used for the toggle to match the ngbDropdownItem. How should this be handled?

2022-09-23 06:07 UTC, KorakotSanti commented on UI/Web/src/app/cards/card-item/card-actionables/card-actionables.component.ts
> +      this.canDownload = this.accountService.hasDownloadRole(user);
I moved the cdmarkforcheck inside the subscribe block, I haven't taken care of changing the admin or download role into an observable yet.

2022-09-23 11:22 UTC, majora2007 commented on UI/Web/src/app/cards/card-item/card-actionables/card-actionables.component.scss
> +    font-weight: 400;
It needs to be called out in the changelog is all. Just put under Added. Users aren't going to comb through dependencies.

2022-09-23 14:36 UTC, majora2007 commented on UI/Web/src/app/cards/card-item/card-actionables/card-actionables.component.scss
> +    font-weight: 400;
Actually I'm going to leave these off, since I don't think they should be overridden.

2022-09-23 14:37 UTC, majora2007 approved these changes
Thanks for taking care of my comments, I will take care of the observables as I need this code in my branch.

2022-09-23 14:37 UTC, merged