Spelling, grammar, and related consistency improvements
Kareadita/Kavita pull request #1756
Opened 2023-01-23 14:17 UTC by DomenicF

Hey all! I have been using Kavita for a while now and noticed some simple spelling/grammar mistakes and consistency issues.

# Changed
- Changed: 'Want To Read' to 'Want to Read' where found.
- Changed: Email description text to read in a more fluid fashion.
- Changed: 'url' and 'Url' to 'URL' where found.
- Changed: Tooltip text 'covert' to 'convert' OR 'cover' where applicable/found.
- Changed: Tooltip text 'place' to 'places' where applicable/found.
- Changed: Statistics sending description to read in a more fluid fashion.
- Changed: The word 'manga' to 'library' in the library scan tooltip.
- Changed: 'Usefull' to 'Useful' where found.
- Changed: WebStorm removed some trailing spaces in the files that I changed. If you want this reverted, let me know.

I am sure that I have missed some things, but, I think this is a good start. Please let me know if there is anything that I can change with this PR or if it's completely unnecesary.

Thanks for your time!

2023-01-31 16:09 UTC, DomenicF commented
Hi - just checking in. Any issues or comments?

2023-02-01 00:43 UTC, majora2007 requested changes
Just one small enhancement to reflect some new features in Kavita and I can merge.

2023-02-01 00:43 UTC, majora2007 commented on UI/Web/src/app/admin/manage-email-settings/manage-email-settings.component.html
> +            Registration/confirmation emails will not be sent if you are not accessing Kavita via a publicly reachable URL.
Can you reword this in retrospect to include that:
Registration/confirmation emails will not be sent if you are not accessing Kavita via a publicly reachable URL or unless Host Name is configured.

Host name is a new feature that allows you to specify the reverse proxy used to access Kavita and hence Kavita will assume that for email generation and override the check if accessible.

2023-02-03 21:23 UTC, DomenicF commented
Done. Let me know if that's what you wanted or if I misunderstood.

2023-02-04 00:22 UTC, majora2007 approved these changes

2023-02-04 00:24 UTC, merged