Added vertical reading mode to the book reader
Kareadita/Kavita pull request #1787
Opened 2023-02-13 18:56 UTC by CKolle

# Added
- Added: Vertical reading mode support added to the web-based book reader. This feature is particularly useful for reading genres like Japanese light novels. The API backend and settings user interface have also been updated to allow users to switch between horizontal and vertical reading modes
# Changed
- Changed: Margin handling has been refined. The units were changed from percentage (%) to viewport width (vw) to accommodate resizing when the reading direction is set to right-to-left (rtl).

2023-02-13 19:59 UTC, majora2007 requested changes
Preliminary glance over looks pretty good. After v0.7 releases I will pull this down and give a indepth review.

2023-02-13 19:59 UTC, majora2007 commented on API/Entities/Enums/ReadingMode.cs
> +    Vertically = 0,
Add [Description()] annotation like other enums

2023-02-13 19:59 UTC, majora2007 commented on UI/Web/src/app/book-reader/_components/book-reader/book-reader.component.ts
> +       console.log("Scrolling to end of page");
Remove console.log

2023-02-13 19:59 UTC, majora2007 commented on UI/Web/src/app/book-reader/_components/book-reader/book-reader.component.ts
> +        this.reader.nativeElement.children
Remove dead code

2023-02-13 19:59 UTC, majora2007 commented on UI/Web/src/app/book-reader/_components/book-reader/book-reader.component.ts
> +        //this.scrollService.scrollToX((currentVirtualPage - 2) * pageWidth, this.bookContentElemRef.nativeElement);
Remove dead code

2023-02-13 19:59 UTC, majora2007 commented on UI/Web/src/app/book-reader/_components/book-reader/book-reader.component.ts
> +          this.scrollService.scrollTo( (currentVirtualPage) * pageWidth, this.bookContentElemRef.nativeElement, "auto");
Use single quotes in javascript

2023-02-13 19:59 UTC, majora2007 commented on UI/Web/src/app/book-reader/_components/book-reader/book-reader.component.ts
> +    const currentVirtualPage = Math.min(Math.max(1, Math.round((scroll + pageSize) / pageSize)), totalVirtualPages);
Put my comment back because I always forget how virtual page math works.

2023-02-13 19:59 UTC, majora2007 commented on UI/Web/src/app/book-reader/_components/reader-settings/reader-settings.component.ts
> +          console.log('Reading mode is undefined  - setting to horizontal');
Remove dead code

2023-02-24 20:13 UTC, majora2007 commented
I haven't forgotten about this, I will be on holiday until next week. I have this planned for a code review and extensive testing shakeout.

2023-03-04 13:57 UTC, majora2007 commented
Here are some issues I faced:
-  Vertical/Horizontal is always showing flipped on ebook menu. When I'm in Horizontal, it's showing Vertical as the label. (Edit: I'm just realizing it's because that's how the text flows. I think this may be confusing and we should use how the page is read vs how the text is laid out)
- I cannot get Horizontal + Scroll to work. It's always clamping at 1 column and I have to use Tap to Paginate to move pages. I was finally able to trigger it by going to 2 column then back to scroll (on vertically), but scroll via mouse isn't possible. 

Once it's functionally working, I will do a code review. Overall, it feels really good though and outside of those small issues, this looks like a huge improvement. I really appreciate the PR.

2023-03-04 13:58 UTC, majora2007 requested changes
See comment above

2023-03-04 15:54 UTC, CKolle commented
I will look into the the issues

2023-03-05 17:14 UTC, CKolle commented
I have now addressed the issues you faced and squashed some bugs I found regarding pagination in vertical scroll mode, and images getting a little cropped.

2023-03-05 20:02 UTC, majora2007 commented
I'm getting build errors.

horizontalScrollbarNeeded isn't defined on book-reader.component.ts

2023-03-05 20:54 UTC, CKolle commented
Sorry about that I forgot to commit a line, I must have thought it was an unnecessary white-space or something. Anyways did a fresh git clone and tested it, and it seems to be working fine.

2023-03-05 23:15 UTC, majora2007 reviewed
Mostly looking good, a few comments.

2023-03-05 23:15 UTC, majora2007 commented on UI/Web/src/app/book-reader/_components/book-reader/book-reader.component.ts
> +    let columnGap = 20
Make this const

2023-03-05 23:15 UTC, majora2007 commented on UI/Web/src/app/book-reader/_components/book-reader/book-reader.component.ts
> +    const columnGap = 20;
Move this and the other into one at the top. We shouldn't have 2 constants in diferent places.

2023-03-05 23:15 UTC, majora2007 commented on UI/Web/src/app/book-reader/_components/book-reader/book-reader.component.ts
> +    const [scroll, total] = this.getScrollAndTotal();
I'd prefer to keep the variable names scrollOffset and totalScroll

2023-03-05 23:15 UTC, majora2007 commented on UI/Web/src/app/book-reader/_components/book-reader/book-reader.component.ts
> +      setTimeout(() => this.scrollService.scrollToX(scrollLeft, this.reader.nativeElement, "smooth"), 10);
Please use single quotes in the javascript

2023-03-05 23:15 UTC, majora2007 commented on UI/Web/src/app/book-reader/_components/book-reader/book-reader.component.ts
> +      if (resumeElement !== null && resumeElement !== undefined) {
this can just be if (resumeElement)

and you can remove the typing from resumeElement as IDE can infer from getFirstVisibleElementXPath

2023-03-05 23:15 UTC, majora2007 commented on UI/Web/src/app/book-reader/_components/reader-settings/reader-settings.component.html
> +                    <label id="writingstyle" class="form-label">Writing Style <i class="fa fa-info-circle" aria-hidden="true" placement="top" [ngbTooltip]="writingStyleTooltip" role="button" tabindex
this should be writing-style. For any ids in html, it should be kebab case.

2023-03-05 23:15 UTC, majora2007 commented on UI/Web/src/app/book-reader/_components/reader-settings/reader-settings.component.html
> +                    <label id="writingstyle" class="form-label">Writing Style <i class="fa fa-info-circle" aria-hidden="true" placement="top" [ngbTooltip]="writingStyleTooltip" role="button" tabindex
You also need a span with writingStyle-help as an id so the screenreader announces what's in the tooltip. Look around and you should find an example

2023-03-05 23:15 UTC, majora2007 commented on UI/Web/src/app/book-reader/_components/reader-settings/reader-settings.component.html
> +                    <ng-template #writingStyleTooltip>Changes the direction of the text. Horizontal is left to right, vertical is top to bottom.</ng-template>
This seems non-intuitive for first time user, but i can't think of a better description right now.

2023-03-05 23:15 UTC, majora2007 commented on UI/Web/src/app/user-settings/user-preferences/user-preferences.component.html
> +                                        <label for="settings-book-reading-style" class="form-label">Writing Style</label>&nbsp; <i class="fa fa-info-circle" aria-hidden="true" placement="right" [ngbT
Don't use nbsp&;, use mr-2 class (search around you'll see the correct class)

2023-03-05 23:15 UTC, majora2007 commented on UI/Web/src/app/user-settings/user-preferences/user-preferences.component.html
> +                                        <label for="settings-book-reading-style" class="form-label">Writing Style</label>&nbsp; <i class="fa fa-info-circle" aria-hidden="true" placement="right" [ngbT
You need the aria-describeby="settings-book-writing-style-help" so the screenreader understands the tooltip message

2023-03-06 14:48 UTC, majora2007 reviewed
Almost there

2023-03-06 14:48 UTC, majora2007 commented on UI/Web/src/app/book-reader/_components/book-reader/book-reader.component.ts
> +  columnGap: number = 20;
Move this to a const outside the class since it's not changing. Then you don't need to access on this.

2023-03-06 17:39 UTC, majora2007 approved these changes
LGTM

2023-03-06 20:02 UTC, merged