Add timezone and more comments to docker-compose.yml
Kareadita/Kavita pull request #2233
Opened 2023-08-24 10:41 UTC by ameer1234567890

# Added
- Added: Added time zone in docker-compose.yml
- Added: Added more comments in docker-compose.yml

2023-08-24 12:44 UTC, majora2007 commented
Why are you removing port and restart lines? These comments are already found on the wiki and docker site to explain.

2023-08-24 14:15 UTC, Kizaing commented
You can actually remove the version: line entirely, the docker compose v2 spec no longer requires it. You can also keep ./config the same, it doesn't need to be renamed to ./data

2023-08-24 14:16 UTC, therobbiedavis commented
> Why are you removing port and restart lines? These comments are already found on the wiki and docker site to explain. 

They were not removed, Joe.

A better format would be to mark the additional lines as `#OPTIONAL`. Clear, succinct, and follows the format of basically every other compose.

2023-08-26 13:38 UTC, majora2007 requested changes
Please take care of these comments then we can merge.

2023-08-26 13:38 UTC, majora2007 commented on docker-compose.yml
> +            - ./data:/kavita/config     # Change './data if you want to have the config files in a different place.
Leave this as config instead of data. Comment is fine, but config will make it easier when supporting users.

2023-08-26 13:38 UTC, majora2007 commented on docker-compose.yml
> +version: '3.9'
Remove this as it's no longer needed

2023-08-26 13:38 UTC, majora2007 commented on docker-compose.yml
> +            - ./books:/books            #
Use OPTIONAL for the comics and books, like Robbie suggested.

2023-08-28 12:36 UTC, majora2007 approved these changes

2023-08-29 23:06 UTC, majora2007 commented
Okay I'm back from holiday. Why are you modifying this docker-compose.yml? This isn't used anywhere in the dev or production code. It seems like you'd want to modify our wiki instead.

2023-08-30 17:52 UTC, majora2007 commented
That's not a good enough reason, I think we should in fact delete the compose file completely. It's not used as dev resource and I don't want to maintain extra files if there is no point. Users should not be coming to the source code to find files to learn how to run the software. @therobbiedavis and @Kizaing can I get your thoughts on this?

2023-08-30 18:13 UTC, therobbiedavis commented
@majora2007 Honestly it is common for open source products to contain the compose file to run within their repo since that is where a lot of people initially go for documentation. I don't see an issue with having it since it's like a one and done file, however if you do not want to maintain it then we should remove it entirely.

2023-08-30 23:14 UTC, majora2007 commented
I've decided to decline this PR and delete the original file. This PR is testament to the compose file not being needed as timezone was added long ago on the wiki and all other documentation. I honestly didn't even notice we had a compose in the application, otherwise it would have been updated when we updated our documentation. 

I will take your comments and update the wiki documentation as it may help users understand how volume mounts work better. 

Thanks for raising the PR in the first place, enhancement was drawn from your effort, just not in the way initially expected.

2023-08-30 23:14 UTC, closed without merging