feature/book reader swipe pagination
Kareadita/Kavita pull request #2754
Opened 2024-02-29 07:59 UTC by ShivamAmin

# Added
- Added: Setting to toggle swipe to paginate setting in reader settings
- Added: Disable text highlighting when menu is hidden and swipe to paginate is enabled
- Added: Swipe to change page functionality using swipe distance (30% screen threshold) (Idea: #2666 )
- 

# Changed
- Changed: Swipe to change page functionality now also uses speed (distance/time) to determine whether to paginate.

# Fixed
- Fixed: Fixed a bug where the user is able to soft lock the book reader by enabling immersive mode but disabling click to paginate
- Fixed: Disable click to paginate boxes when action bar is visible (fixes #2694)

# TODO
- Add: User preference setting to configure swipe to paginate (Requires DB Update)
- Nice to have: Swipe animations (May be more effort than worth?)
- Suggestions welcome

2024-02-29 20:29 UTC, ShivamAmin commented
I added the toggle for this feature to the user preferences page, but for it to work we need to add the migration. I've done this before, but I can't figure out how it's done in this library. I'm happy to read documentation and add it myself

2024-02-29 20:53 UTC, majora2007 commented
To add the migration you add the setting to the user preferences entity then type `dotnet ef migrations add MigrationNameHere`.

Review the SQL and launch Kavita to have it applied.

2024-02-29 21:27 UTC, ShivamAmin commented
> To add the migration you add the setting to the user preferences entity then type `dotnet ef migrations add MigrationNameHere`.
> 
> Review the SQL and launch Kavita to have it applied.

Great, I'll also see about adding this to the readme or somewhere so it's documented,

2024-03-09 21:24 UTC, majora2007 commented
Just an FYI, I am still planning to review this. I have all bugfixes and PRs on hold until I wrap this comic rework. I'm really curious to see how this works and go through the code.

2024-03-30 19:24 UTC, majora2007 commented
Hey, just curious if you're up for fixing merge conflicts? I have wrapped the comic rework stuff and there is time to review this and see if it can make the v0.8 release.

2024-04-07 00:16 UTC, ShivamAmin commented
> Hey, just curious if you're up for fixing merge conflicts? I have wrapped the comic rework stuff and there is time to review this and see if it can make the v0.8 release.

Sorry it took a while, but the merge conflicts have been resolved, and I tried to clean up the commit history

2024-04-07 14:58 UTC, majora2007 commented
Thanks, I'll review the PR this week. Looks like quite a big one.

2024-06-02 13:08 UTC, majora2007 commented
Hey, sorry I haven't tackled this yet. It's a big PR with a lot of different things added in (for future reference, smaller PRs that are directed with one feature is much better for me). 

It's in my mind, but not a priority until I have enough time to really tackle and test.

2024-06-29 15:26 UTC, majora2007 requested changes
Some initial testing:
- Overflow issue on the tooltip and tooltip is on second line
![image](https://github.com/Kareadita/Kavita/assets/735851/6dd5ec1e-86d8-4bc1-af8c-8b00b1e35e8d)

- Doesn't seem like I can trigger it on default settings with dev tools responsive mode (which works for my implementation of swipe to paginate on the manga reader). Can you provide guidance? 

- I like this design, but we probably want a reset to default button on the right side to reset if we changed it. 
![image](https://github.com/Kareadita/Kavita/assets/735851/3be905ff-48c9-46b1-942a-b2b7aafdbe9b)

- Immersive mode is no longer working. I have it enabled with swipe pagination but the action bars are still visible

- Swipe should be disabled on Non-column mode in my opinion

- Swipe mode (and Tap to paginate) should be enabled on non-immersive mode. Not sure why you changed this.

- Since I can't test swipe pagination I cannot confirm, but did you test this with vertical writing mode? 

- Tap pagination is completely broke as well, so I can't test the fix with the menu popping. 


I did not review the code yet. But based on initial surface level testing, this def needs a lot of work. 

I would recommend doing this into pieces with smaller PRs tackling one thing at a time. Much easier on me to review and test and much more likely to get changes merged sooner.

2025-11-07 21:02 UTC, closed without merging