Allowing admin users to change users email
Kareadita/Kavita pull request #3118
Opened 2024-08-18 23:41 UTC by DieselTech

# Changed
- Changed: Allowing admins to edit user profiles to update their email addresses. (Closes https://github.com/Kareadita/Kavita/issues/2647)

2024-08-21 11:17 UTC, majora2007 requested changes
Just did a preliminary review. I don't see any of the email code to trigger a link so the user can confirm the email change.

2024-08-21 11:17 UTC, majora2007 commented on API/Controllers/AccountController.cs
> +            user.Email = dto.Email;
You need a new line after the if statement to help the code be easier to digest.

2024-08-21 11:17 UTC, majora2007 commented on API/Controllers/AccountController.cs
> +            user.ConfirmationToken = await _userManager.GenerateEmailConfirmationTokenAsync(user);
You generate a confirmation token, but I don't see you triggering an email for the end user to confirm and get rid of that pending status.

2024-10-08 21:18 UTC, majora2007 commented
Not sure if you still want to work on this to get it in?

2024-10-09 19:23 UTC, DieselTech commented
Changes made. Got rid of the email confirmation step because it is an admin making the change. That should force change it and not rely on the confirmation flow. Not sure what I was thinking before.

2024-12-08 16:13 UTC, majora2007 commented
I'm going to implement this myself, it's going to be much easier. I'll dm you the correct way to implement this.

2024-12-08 16:13 UTC, closed without merging

2024-12-08 18:35 UTC, majora2007 commented
Here is the correct way to implement:
https://github.com/Kareadita/Kavita/pull/3446/commits/d522bccf86cb11efd1b59e380bbbc446c2c6ba35